#pragma once

namespace ltnc {
	enum class ErrorCode {
		NO_CODE = 0,
		NO_MAIN,

		UNEXPECTED_TOKEN = 100,

		EXPECTED_DECLARATION = 200,
		EXPECTED_STATEMENT,
		EXPECTED_EXPRESSION,
		EXPECTED_SEMICOLON,
		EXPECTED_PAREN_L,
		EXPECTED_PAREN_R,
		EXPECTED_BRACE_L,
		EXPECTED_BRACE_R,
		EXPECTED_COMMA,
		EXPECTED_EQUAL,
		EXPECTED_IDENTIFIER,


		UNNAMED_FUNCTION,
		UNCLOSED_PARAMETER_LIST,
		UNOPENED_PARAMETER_LIST,
		UNNAMED_PARAMETER,
		VOID_PARAMETER,
		MISSING_RETURN_TYPE,
		
		UNNAMED_NAMESPACE,

		UNOPENED_ASM_BLOCK,
		UNCLOSED_ASM_BLOCK,

		UNNAMED_STRUCT,
		UNNAMED_TYPE,
		UNNAMED_VARIABLE,

		MISSING_CONDITION,
		MISSING_IF_BRANCH,

		MALFORMED_WHILE,
		MALFORMED_FOR,
		MALFORMED_REPEAT,

		UNDEFINED_IDENTFIER = 200,
		UNDEFINED_FUNCTION,
	};
}