#pragma once

namespace ltn {
	enum class MemberCode {
		OPERATOR_ADD = 0x10, OPERATOR_SUB, OPERATOR_MLT, OPERATOR_DIV, OPERATOR_MOD, OPERATOR_POW,
		OPERATOR_STR = 0x20, OPERATOR_CMP, OPERATOR_BOOL,
	};
}
	