#pragma once
#include <cstdint>

// formats
// c,v,s 	-> 32 16 8 opcode(8)
// j 		-> 56      opcode(8)

enum class InstCode : std::uint8_t {
	EXIT = 0x00, 
	ERROR, 
	SCRAP,
	CLEAR,
	PRINT,
	FETCH,
	NEWL, NEWU,
	LOAD, STORE, COPY, SIZE,
	INIT, STACKALLOC,
	
	CALL = 0x10, GOTO, RETURN, IFSK,

	ADDI = 0x20, SUBI, MLTI, DIVI, POWI, MODI, CASTI, INCI, DECI, MNSI, MINI, MAXI,
	ADDF = 0x30, SUBF, MLTF, DIVF, POWF, MODF, CASTF, INCF, DECF, MNSF, MINF, MAXF,
	
	BITOR = 0x40, BITAND, BITXOR, LOGOR, LOGAND, LOGXOR, EQLI, SMLI, BGRI, SPSHI, EQLF, SMLF, BGRF, SPSHF,

		
	HEAP_DEL = 0xa0, HEAP_EXIST, HEAP_COPY,
	
	ARRAY_NEW = 0xb0, ARRAY_CLR, ARRAY_GET, ARRAY_SET, ARRAY_LEN, ARRAY_FLL, ARRAY_RSZ, ARRAY_INS, ARRAY_ERS,
	ARRAY_PUSHF, ARRAY_PUSHB, 
	ARRAY_POPF, ARRAY_POPB,
	ARRAY_GETF, ARRAY_GETB,
	
	STRING_NEW = 0xc0, STRING_ADD, STRING_DATA, STRING_PRINT,

	STACK_NEW = 0xd0, STACK_PUSH, STACK_POP, STACK_EMPTY, STACK_SIZE, STACk_CLEAR, STACK_TOP,
	QUEUE_NEW = 0xd8, QUEUE_PUSH, QUEUE_POP, QUEUE_EMPTY, QUEUE_SIZE, QUEUE_CLEAR, QUEUE_FRONT,
	DEQUE_NEW = 0xe0, DEQUE_EMPTY, DEQUE_SIZE, DEQUE_CLEAR,
	DEQUE_PUSHF, DEQUE_PUSHB,
	DEQUE_FRONT, DEQUE_BACK, 
	DEQUE_POPF, DEQUE_POPB, 

	EXT0 = 0xf0, EXT1, EXT2, EXT3, EXT4, EXT5, EXT6, EXT7,
	LOOP_RANGE, LOOP_INF, LOOP_CONT, LOOP_STOP, LOOP_IDX,

};