#pragma once
#include <unordered_map>
#include <string_view>
#include <tuple>
#include "ltn/InstructionSet.hxx"
namespace ltn::a {
	enum struct InstArgs {
		NONE,
		UINT, UINTx2,
		INT,
		FLOAT,
		BYTE,
		CHAR,
		CHAR_4,
		CHAR_8,
	};
	using namespace std::string_view_literals;
	
	using InstructionData = std::tuple<Inst, std::size_t, InstArgs>;
	
	using InstructionTable = std::unordered_map<
		std::string_view,
		InstructionData>;
	
	const InstructionTable instructionTable{
		{"add", {Inst::ADD, 1, InstArgs::NONE}},
		{"sub", {Inst::SUB, 1, InstArgs::NONE}},
		{"mlt", {Inst::MLT, 1, InstArgs::NONE}},
		{"div", {Inst::DIV, 1, InstArgs::NONE}},
		{"mod", {Inst::MOD, 1, InstArgs::NONE}},
		{"eql", {Inst::EQL, 1, InstArgs::NONE}},
		{"ueql", {Inst::UEQL, 1, InstArgs::NONE}},
		{"sml", {Inst::SML, 1, InstArgs::NONE}},
		{"bgr", {Inst::BGR, 1, InstArgs::NONE}},
		{"smleql", {Inst::SMLEQL, 1, InstArgs::NONE}},
		{"bgreql", {Inst::BGREQL, 1, InstArgs::NONE}},
		{"shift_l", {Inst::SHIFT_L, 1, InstArgs::NONE}},
		{"shift_r", {Inst::SHIFT_R, 1, InstArgs::NONE}},
		{"neg", {Inst::NEG, 1, InstArgs::NONE}},
		{"not", {Inst::NOT, 1, InstArgs::NONE}},
		{"inc", {Inst::INC, 1, InstArgs::NONE}},
		{"dec", {Inst::DEC, 1, InstArgs::NONE}},
		{"newu", {Inst::NEWU, 9, InstArgs::UINT}},
		{"newi", {Inst::NEWI, 9, InstArgs::INT}},
		{"newf", {Inst::NEWF, 9, InstArgs::FLOAT}},
		{"newfx", {Inst::NEWFX, 17, InstArgs::UINTx2}},
		{"newclock", {Inst::NEWCLOCK, 1, InstArgs::NONE}},
		{"true", {Inst::TRUE, 1, InstArgs::NONE}},
		{"false", {Inst::FALSE, 1, InstArgs::NONE}},
		{"newarr", {Inst::NEWARR, 1, InstArgs::NONE}},
		{"newstr", {Inst::NEWSTR, 1, InstArgs::NONE}},
		{"newout", {Inst::NEWOUT, 2, InstArgs::BYTE}},
		{"newin", {Inst::NEWIN, 2, InstArgs::BYTE}},
		{"null", {Inst::NVLL, 1, InstArgs::NONE}},
		{"char", {Inst::CHAR, 2, InstArgs::CHAR}},
		{"elem", {Inst::ELEM, 1, InstArgs::NONE}},
		{"char_4", {Inst::CHAR_4, 5, InstArgs::CHAR_4}},
		{"char_8", {Inst::CHAR_8, 9, InstArgs::CHAR_8}},
		{"jump", {Inst::JUMP, 9, InstArgs::UINT}},
		{"call", {Inst::CALL, 9, InstArgs::UINT}},
		{"return", {Inst::RETURN, 1, InstArgs::NONE}},
		{"ifelse", {Inst::IF, 9, InstArgs::UINT}},
		{"error", {Inst::ERROR, 1, InstArgs::NONE}},
		{"exit", {Inst::EXIT, 1, InstArgs::NONE}},
		{"invoke", {Inst::INVOKE, 1, InstArgs::NONE}},
		{"external", {Inst::EXTERNAL, 1, InstArgs::NONE}},
		{"read", {Inst::READ, 1, InstArgs::NONE}},
		{"write", {Inst::WRITE, 1, InstArgs::NONE}},
		{"scrap", {Inst::SCRAP, 1, InstArgs::NONE}},
		{"makevar", {Inst::MAKEVAR, 1, InstArgs::NONE}},
		{"at", {Inst::AT, 1, InstArgs::NONE}},
		{"at_write", {Inst::AT_WRITE, 1, InstArgs::NONE}},
		{"read_x", {Inst::READ_X, 9, InstArgs::UINT}},
		{"write_x", {Inst::WRITE_X, 9, InstArgs::UINT}},
		{"read_0", {Inst::READ_0, 1, InstArgs::NONE}},
		{"read_1", {Inst::READ_1, 1, InstArgs::NONE}},
		{"read_2", {Inst::READ_2, 1, InstArgs::NONE}},
		{"read_3", {Inst::READ_3, 1, InstArgs::NONE}},
		{"write_0", {Inst::WRITE_0, 1, InstArgs::NONE}},
		{"write_1", {Inst::WRITE_1, 1, InstArgs::NONE}},
		{"write_2", {Inst::WRITE_2, 1, InstArgs::NONE}},
		{"write_3", {Inst::WRITE_3, 1, InstArgs::NONE}},
		{"out", {Inst::OUT, 1, InstArgs::NONE}},
		{"in_str", {Inst::IN_STR, 1, InstArgs::NONE}},
		{"in_line", {Inst::IN_LINE, 1, InstArgs::NONE}},
		{"in_int", {Inst::IN_INT, 1, InstArgs::NONE}},
		{"in_float", {Inst::IN_FLOAT, 1, InstArgs::NONE}},
		{"is_eof", {Inst::IS_EOF, 1, InstArgs::NONE}},
		{"min", {Inst::MIN, 1, InstArgs::NONE}},
		{"max", {Inst::MAX, 1, InstArgs::NONE}},
		{"round", {Inst::ROUND, 1, InstArgs::NONE}},
		{"floor", {Inst::FLOOR, 1, InstArgs::NONE}},
		{"ceil", {Inst::CEIL, 1, InstArgs::NONE}},
		{"abs", {Inst::ABS, 1, InstArgs::NONE}},
		{"hypot", {Inst::HYPOT, 1, InstArgs::NONE}},
		{"sqrt", {Inst::SQRT, 1, InstArgs::NONE}},
		{"sin", {Inst::SIN, 1, InstArgs::NONE}},
		{"cos", {Inst::COS, 1, InstArgs::NONE}},
		{"tan", {Inst::TAN, 1, InstArgs::NONE}},
		{"size", {Inst::SIZE, 1, InstArgs::NONE}},
		{"front", {Inst::FRONT, 1, InstArgs::NONE}},
		{"back", {Inst::BACK, 1, InstArgs::NONE}},
		{"to_seconds", {Inst::TO_SECONDS, 1, InstArgs::NONE}},
		{"typeid", {Inst::TYPEID, 1, InstArgs::NONE}},

	};
}